### ISSUE TITLE
real-time preference update of accent color

### ISSUE THREAD

**Issue by thetrotfreak** [thetrotfreak/spd-client#3]
### Log
```
Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'color_scheme_seed'")>
Traceback (most recent call last):
  File "C:\Users\bivas\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\spd\spd-client\controls\menu.py", line 42, in <lambda>
    on_click=lambda event: MaterialYouCustomizationDialog(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\spd\spd-client\controls\material.py", line 33, in __init__
    controls=[*map(lambda color: self.button(color), Preference.__COLORS__)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\spd\spd-client\controls\material.py", line 33, in <lambda>
    controls=[*map(lambda color: self.button(color), Preference.__COLORS__)]
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\spd\spd-client\controls\material.py", line 38, in button
    if color.casefold() == self.page.theme.color_scheme_seed.casefold():
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'color_scheme_seed'
```
### Expected

- A dialog box to let the user select from a bunch of accent colors.
- Preference should be updated in a way making sure the rest of the UI refreshes with the new accent color.

**Comment by thetrotfreak** [comment]
fixed https://github.com/thetrotfreak/spd-client/commit/cad6fc7312a89175d9fab67f33cb50080bc75f00
